version: "3.8"

services:
  app:
    build:
      context: ./app

  promtail:
    build:
      context: ./promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  loki:
    build:
      context: ./loki

  grafana:
    build:
      context: ./grafana
    volumes:
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
